steps:
  - command: |
      time npm install
      npm run test
    plugins:
      - namespacelabs/nscache#v0.1
    agents:
      nsc-base-image-ref: node
      nsc-cache-tag: buildkite-demo-remix/npm-cache
